### ISSUE TITLE
Add wait period to script

### ISSUE THREAD

**Issue by timmmmyboy** [letsencrypt-cpanel/whmcs_hook#1]
I know at least in our instance this hook would be firing alongside with a new domain registration and it appears modules come before the actual registration so by the time the hook is attempting to provision an SSL cert the domain is not yet resolving. Is there a good way to add in a wait period here? I think even 60-120 seconds might be enough for the domain to get registered and resolve. Alternatively it may make sense at least as a first measure for the plugin to make staggered regular attempts at provisioning a cert if it fails on first attempt.

**Comment by alexzorin** [comment]
Belongs in daemon for sure.

Here is current idea:
- `run_autossl_for_user_async` will gain `bool retry` flag.
- WHMCS hook will pass `true` for retry
- If daemon experiences DCV preflight failure (which covers domain not registered or not resolving) and `retry` is set, it will write it back to `autossl_deferred` bucket).
- Every minute, the daemon will process the `autossl_deferred` bucket, with exponential backoff on each entry until `MAX_ATTEMPTS`.

Let me know if this is conceptually suitable for your case

**Comment by alexzorin** [comment]
This will go into the next release, but we will not be pushing that for at least a week, to allow a chance for bug reports for 0.7.0 to come in.

I have published the rpms for you in the mean time here, if you wish to use them:

https://plugindev.serversaurus.com.au/letsencrypt-cpanel-0.7.1-1.i386.rpm
https://plugindev.serversaurus.com.au/letsencrypt-cpanel-0.7.1-1.x86_64.rpm

**Comment by timmmmyboy** [comment]
This sounds great, especially the exponential backoff. That was my only major concern with "if it fails try again" for folks who are transferring a domain as part of signing up for an account so they woudn't have an active one resolving on our server for in many cases days. Thanks for the quick work on this!
